/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_calculator_models_Model */

#ifndef _Included_com_example_calculator_models_Model
#define _Included_com_example_calculator_models_Model
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_calculator_models_Model
 * Method:    parsingStr
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_calculator_models_Model_parsingStr
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
